spring.application.name=eureka-server
server.port=8761

# This IS the registry, so it shouldn't register with itself or fetch a registry.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost
